# Generated by Django 3.0.5 on 2020-04-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='recoveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='increase_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='recoveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='increase_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='recoveries',
            field=models.IntegerField(default=0),
        ),
    ]
