# Generated by Django 3.0.5 on 2020-04-13 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200412_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
