# Generated by Django 3.0.5 on 2020-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200419_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='cases',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='deaths',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='recoveries',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
