# Generated by Django 3.0.5 on 2020-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200419_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='coefficient',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='predicted',
            field=models.FloatField(default=0),
        ),
    ]
