# Generated by Django 3.0.5 on 2020-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200419_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='null', max_length=30)),
                ('hits', models.CharField(default='null', max_length=30)),
                ('user_agent', models.CharField(default='null', max_length=30)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
