# Generated by Django 3.0.5 on 2020-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='hits',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(default='null', max_length=60),
        ),
    ]
