# Generated by Django 3.0.5 on 2020-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200420_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
